### PR TITLE
Only notify once for each pokemon found

### PR DESCRIPTION
**Pull request by coolius**
Should stop multiple notifications for the same pokemon

### CODE REVIEW

**Comment by jxmorris12** [comment]
thanks, needed this!

**Comment by Bassir** [comment]
After all spawn points have been exhausted, this implementation does not notify you any longer, even if something you are interested in pops up.

**Comment by coolius** [comment]
I don't understand what you mean by "after all the spawn points have been exhausted"?

Pokemon are deleted from the dictionary when they are cleared so a new pokemon will always create a new entry won't it?

**Comment by padenshorey** [comment]
I get a similar issue but it's not caused by this pull. Eventually, the visible list will stop populating for some reason... still trying to figure it out but testing is hard as I have to wait 15-25 minutes before it starts acting this way after running the code.

**Comment by Bassir** [comment]
@padenshorey Maybe that's the issue. It stops populating. I thought it was related to this pull, but I'm still unsure.

**Pull request merged**
