### PR TITLE
Refactor how login is memoized, and clear login on AttributeError

### PR DESCRIPTION
**Pull request by karlhe**
This pull request includes a
- [x] Bug fix
- [ ] New feature
- [ ] Translation

The following changes were made
- Change how `login` is memoized
- Reset login when AttributeError is encountered

Extracted from a commit on my fork. This should fix the problem described in issue #26

### CODE REVIEW

**Comment by coolius** [comment]
Tried this out - ran for 90mins before getting an error

**Comment by karlhe** [comment]
Can you paste your error?

**Comment by Silvawar14** [comment]
I got an error after 20 minutes.

After queueing,
http://pastebin.com/RD9vCW82

**Comment by karlhe** [comment]
Are you using PTC login? I was never able to make a PTC account so I couldn't test it out, unfortunately.

Maybe try adding `access_token = None` back to line 58 in `main.py`?

**Comment by coolius** [comment]
Adding that line back in makes no difference I'm afraid. Using PTC account, same error as Silvawar14

**Pull request merged**
