### PR TITLE
Add option to push to a channel

### PR DESCRIPTION
**Pull request by arneson**
This pull request includes a
- [ ] Bug fix
- [X] New feature
- [ ] Translation

The following changes were made
## 

If this is related to an existing ticket, include a link to it as well.

### CODE REVIEW

**Comment by malosaa** [comment]
#retrieve a channel by its channel_tag. Note that an InvalidKeyError is raised if the channel_tag does not exist
    my_channel = pushbullet_client.get_channel('YOURNAMEHERE')
push = pushbullet_client.push_link(notification_text, google_maps_link, body=location_text, channel=my_channel)

**Comment by malosaa** [comment]
i got also a rewritten notify.py  where can i post it ?

**Comment by arneson** [comment]
You fork the repo, make the change, push the code and then create a pull request.

**Comment by malosaa** [comment]
you had a error in your config , i fixed it , and also added modification to the maps to send as link

**Comment by arneson** [comment]
In my config? The config is not pushed to git, each computer has it's own config.

**Comment by malosaa** [comment]
i mean the readme , sorry .
just replace the seperator.

i also updated again my version , give it a try

**Pull request closed without merging**
