### PR TITLE
Making Pushbullet Notification Clickable

### PR DESCRIPTION
**Pull request by kfishster**
- Getting rid of the &24, which is region specific.
- Changed push_note to push_link so that the notification is clickable

### CODE REVIEW

**Comment by jxmorris12** [comment]
good idea about the link

are you sure &24z isn't the zoom level? That's what I had understood it to be

**Comment by arneson** [comment]
@jxmorris12  It is not, it makes the link unusable in Sweden and Norway, at least :)

**Comment by kfishster** [comment]
Tbh, I am not sure what the &24z does, however, as @scanniza said, it breaks the link for me, too. Once I do load a link just with the lat/long, it populates this z variable automatically (for me, its 14z). It seems like it's regional.

EDIT: z is the zoom level! :D However, the max I can zoom is to 21z, so maybe that's what breaks it, unless it's different for different clients.

**Comment by arneson** [comment]
Oh, cool, then I take that back. I do agree that's probably what breaks it though, @kfishster

**Comment by designcrumble** [comment]
@kfishster  
I added 24z as the parameter for zooming from Maps Api. 
z is the zoom level (1-20) . I just found out that the level can be set from 1-20. 
@jxmorris12 Please update the code with z20 so that no more conflicts occur.

**Comment by kfishster** [comment]
@designcrumble, committed the 20z zoom to the map link for this pull request

**Comment by designcrumble** [comment]
@kfishster Way to go man :). Is there anyway we can create an app for android or iOS with this functionality ?

**Comment by kfishster** [comment]
@designcrumble no problem! There is actually a lot of discussion about making mobile apps on the pokemongo dev subreddit: https://www.reddit.com/r/pokemongodev/
Some people already started (and even finished) heh. Most, if not all, of those apps are using the pokemon-map api that this finder is also a fork of. Woot devs! :)

**Comment by deplorableword** [comment]
I've modified mine to use the following string. On iOS at least, this seems to drop a pin to the exact location instead of trying to geocode and guess a local business.

`gMaps = "http://www.google.com/maps/place/"+str(pokemon["lat"]) + "," + str(pokemon["lng"])`

**Comment by malosaa** [comment]
and it would be better if it can send to a channel ? is that possible ?

**Comment by malosaa** [comment]
anyone ?

**Comment by xcheneric** [comment]
Yes, pushing to a channel in the pushbullet.py documentation. Takes 2 lines of code.

It's not better because you have to first identify which channel you want to send to, so it will vary.

**Comment by arneson** [comment]
Do you mean a pushbullet Channel?

**Comment by malosaa** [comment]
yes a pushbullet channel , i need to know what code i can use so it works

**Comment by kfishster** [comment]
@malosaa there is a way to feed it into the channel, here is the code reference: https://github.com/randomchars/pushbullet.py#channels

**Comment by malosaa** [comment]
@kfishster i did try iT but i can't get a code to work.. Can
Anyone help me with iT ?

**Comment by malosaa** [comment]
@kfishster 

i use this :
print(pushbullet_client.channels)
push = pushbullet_client.push_note(notification_text, gMaps, body=location_text, channel=my_channel)

still don't work
get this error 

IndentationError: unindent does not match any outer indentation level

can you make a code for me ?

**Comment by malosaa** [comment]
i got it working hehe

**Comment by arneson** [comment]
@malosaa Good job, I just added a pull request for this feature. 
https://github.com/jxmorris12/PokemonGo-Finder/pull/18

**Pull request merged**
